	create table cadastroPet(
id int auto_increment primary key, 
nomePet varchar(100),
tipo varchar(20),
raca varchar(20),
sexo varchar(20),
cor varchar(20),
dataNascPet datetime,
idade varchar(20),
porte varchar(20),
rgcua int(20),
microchip varchar(5),
nmicrochip int(20),
peso decimal(10,2),
altura decimal(10,2),
adestrado varchar(5),
obspet varchar(100));
